#pragma once
#define DRIVETRAIN_FRONT_LEFT -20
#define DRIVETRAIN_FRONT_RIGHT 11
#define DRIVETRAIN_BACK_LEFT 19
#define DRIVETRAIN_BACK_RIGHT -12

#define ROLLER_SPINNER 1

#define SHOOTER_LEFT -3
#define SHOOTER_RIGHT 4

#define LOADER -2
#define PNEUMATICS 'H'

// legacy
#define REVERSE SHOOTER_LEFT
#define FOREWARD SHOOTER_RIGHT
#define FRONT_LEFT DRIVETRAIN_FRONT_LEFT
#define FRONT_RIGHT DRIVETRAIN_FRONT_RIGHT
#define BACK_LEFT DRIVETRAIN_BACK_LEFT
#define BACK_RIGHT DRIVETRAIN_BACK_RIGHT
